project: dagger-dc-ablation
method: bayes
metric:
  name: reward
  goal: maximize
parameters:
  rollout_round_min_episodes:
    values: [10]
  rollout_round_min_timesteps:
    values: [600]
  iters:
    values: [25]
  layer_size:
    values: [32]
  num_layers:
    values: [7]
  activation_fn:
    values: ["Tanh"]
  ablation:
    values: [ true ]
  cable_q:
    values: [ true,false ]
  cable_q_d:
    values: [ true,false  ]
  cable_w:
    values: [ true,false ]
  cable_w_d:
    values: [ true,false ]
  robot_rot:
    values: [ true,false ]
  robot_rot_d:
    values: [ true,false ]
  robot_w:
    values: [ true,false ]
  robot_w_d:
    values: [ true,false ]
  other_cable_q:
    values: [ true,false ]
  other_robot_rot:
    values: [ true,false ]
  action_d_single_robot:
    values: [ true,false ]

program: train-dagger
command:
  - ${program}
  - "--inp"
  - "training_data/trajectory_1742905670_random_2robots.yaml"
  - "training_data/trajectory_1742905670_random_2robots.yaml"
  - "training_data"
  - "--env"
  - "training_data/env_window_2robots.yaml"
  - "--model_path"
  - "deps/dynobench/models/point_2.yaml"
  - "--validate"
  - "-dc"

