project: dagger-dc-layer_size
method: bayes
metric:
  name: reward
  goal: maximize
parameters:
  rollout_round_min_episodes:
    values: [10]
  rollout_round_min_timesteps:
    values: [600]
  iters:
    values: [40]
  layer_size:
    values: [32]
  num_layers:
    values: [3]
  activation_fn:
    values: ["Tanh"]
  ablation:
    values: [ false ]
  robot_w_d:
    values: [ false ]

program: train-dagger
command:
  - ${program}
  - "--inp_dir"
  - "training_data"
  - "--env"
  - "training_data/env_window_2robots.yaml"
  - "--model_path"
  - "deps/dynobench/models/point_2.yaml"
  - "--validate"
  - "-dc"

