project: thesis
method: bayes
metric:
  name: reward
  goal: maximize
parameters:
  total_timesteps:
    values: [1000, 2000, 4000, 6000]
  rollout_round_min_episodes:
    values: [1, 3, 5]
  rollout_round_min_timesteps:
    values: [200, 400, 600]
  iters:
    values: [3,4,5,6,7, 10, 20, 30]
  layer_size:
    values: [32, 64, 128, 256]
  num_layers:
    values: [2, 3, 4, 5, 6, 7, 8]
  activation_fn:
    values: ["Tanh"]

program: train-dagger
command:
  - ${program}
  - "--inp_dir"
  - "training_data"
  - "--env"
  - "training_data/env_window_2robots.yaml"
  - "--model_path"
  - "deps/dynobench/models/point_2.yaml"
  - "--validation_traj"
  - "training_data/validation/trajectory_forest_2robots.yaml"

