project: dagger-dc
method: bayes
metric:
  name: reward
  goal: maximize
parameters:
  rollout_round_min_episodes:
    values: [1, 3, 5, 7, 10, 12, 15]
  rollout_round_min_timesteps:
    values: [600]
  iters:
    values: [25, 30, 35, 40, 45]
  layer_size:
    values: [32, 64, 128, 256]
  num_layers:
    values: [1, 2, 3, 4, 5]
  activation_fn:
    values: ["Tanh"]
  ablation:
    values: [ true ]
  robot_w_d:
    values: [ false ]

program: train-dagger
command:
  - ${program}
  - "--inp_dir"
  - "training_data"
  - "--env"
  - "training_data/env_window_2robots.yaml"
  - "--model_path"
  - "deps/dynobench/models/point_2.yaml"
  - "--validate"
  - "-dc"

